POST http://127.0.0.1:5000/api/superheroes
Content-Type: application/json

{
    "nickname": "Канеки", 
    "realName": "Канеки Кен",
    "originDescription": "Канеки — скромный и замкнутый молодой человек с одним-единственным близким другом в лице Хидэ. Обычно он тратит своё время на чтение книг, преимущественно новелл. Любимым писателем Канеки является Такацуки Сен, однако при этом Кен признает, что стиль написания книг у этого литератора довольно сложен.",
    "superpowers": ["Кен унаследовал какухо Ризе, что наделило его способностью использовать её кагуне, аномальной регенерацией и увеличенной физической силой. Поскольку Канеки является гибридом, потенциал его способностей выше, чем у среднестатистического полноценного гуля."],
    "catchPhrase": "Неправильный не я... Неправильный весь этот мир. 1000-7..."
}